# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SITE BASICS - Edit these first!
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# For Cloudflare Pages: This will be overridden by the CF_PAGES_URL during build
# Or set your custom domain here once configured
baseURL = "/"
title = "Gaurav"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ABOUT YOU - Your personal info
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[params]
author = "Gaurav"
description = "Personal website"
keywords = "blog,developer,personal"
info = ["Developer", "Creator"]  # Shows under your name
avatarURL = "images/avatar.jpg"  # Put your photo in static/images/
dateFormat = "January 2, 2006"
colorScheme = "auto"  # "auto", "dark", or "light"
customCSS = ["css/custom.css"]

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SOCIAL LINKS - Add/remove as needed
# Icons: https://fontawesome.com/icons (use fa-brands or fa-solid)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
weight = 1
url = "https://www.instagram.com/iam_gauravbansal"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/gaurav-bansal-02a1a0373"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/Gaurav_Bansel"

[[params.social]]
name = "Facebook"
icon = "fa-brands fa-facebook fa-2x"
weight = 4
url = "https://www.facebook.com/share/1aj7uNFt2G/"

[[params.social]]
name = "Threads"
icon = "fa-brands fa-threads fa-2x"
weight = 5
url = "https://www.threads.com/@iam_gauravbansal"

[[params.social]]
name = "Pinterest"
icon = "fa-brands fa-pinterest fa-2x"
weight = 6
url = "https://pin.it/7McWRsdM7"

[[params.social]]
name = "Reddit"
icon = "fa-brands fa-reddit fa-2x"
weight = 7
url = "https://www.reddit.com/u/iamgauravbansal"

[[params.social]]
name = "Discord"
icon = "fa-brands fa-discord fa-2x"
weight = 8
url = "https://discord.gg/2MbPvazW"

[[params.social]]
name = "WhatsApp"
icon = "fa-brands fa-whatsapp fa-2x"
weight = 9
url = "https://wa.me/919812358414"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# NAVIGATION MENU - Top menu links
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "/projects/"

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ADVANCED (usually don't need to touch)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[pagination]
pagerSize = 10

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
